import React from "react";
import BlogSection from "../components/BlogSection";
import CategoryPage from "../components/CategoryPage";
import Footer from "../components/Footer";
import FooterBanner from "../components/FooterBanner";
import NavBar from "../components/NavBar";
import SubscribeComponent from "../components/SubscribeComponent";
import Head from "next/head";

function category() {
  return (
    <div>
      <Head>
        <title>Category</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <CategoryPage />
      <BlogSection />
      <SubscribeComponent />
      <FooterBanner />
      <Footer />
    </div>
  );
}

export default category;
