import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div>
      <Head>
        <title>ento.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className=" text-4xl text-center text-Primary-dark font-jost font-semibold">Ento Website design File setup</h1>
    </div>
  );
}
