import React from "react";
import Head from "next/head";
import DetailsSection from "../components/DetailsSection";

function productPreview() {
  return (
    <div>
      <Head>
        <title>Details</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DetailsSection/>
    </div>
  );
}

export default productPreview;
